import type { MessageInfo } from '@/schemas/gerrit'

/**
 * Filters out automated messages and empty messages, keeping meaningful review activity
 */
export const filterMeaningfulMessages = (messages: readonly MessageInfo[]): MessageInfo[] => {
  return messages.filter((msg) => {
    // Keep messages that have content beyond automated tags
    if (!msg.message || msg.message.trim().length === 0) return false

    // Skip some automated messages but keep build/review status messages
    if (msg.tag === 'autogenerated:gerrit:newPatchSet') return false
    if (msg.tag === 'autogenerated:gerrit:merged') return false

    return true
  })
}

/**
 * Sorts messages by date with newest first
 */
export const sortMessagesByDate = (messages: readonly MessageInfo[]): MessageInfo[] => {
  return [...messages].sort((a, b) => {
    return new Date(b.date).getTime() - new Date(a.date).getTime()
  })
}
